### ISSUE TITLE
Alert: Master branch getting updated without pull requests

### ISSUE THREAD

**Issue by HarjyotKaur** [UBC-MDS/DSCI_552_heather_harjyot_taracyc_analysis#3]
Hi, 

Follow the following steps in order to work with fork-pull request.

- Clone the forked repository locally
- Follow the steps here to set an upstream as your master branch
https://help.github.com/articles/configuring-a-remote-for-a-fork/

- Now when you makes changes to your "forked repository", push them, make a pull request, the other team member will critique it and accept it

- For updating your forked repository, so that it's up to date with the master branch, follow the following steps:
https://help.github.com/articles/syncing-a-fork/

**Comment by heathervant** [comment]
oops yes I just realized i edited the master branch instead of the forked copy. thanks!
